In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Pre-Processing

## Data Importing

In [1]:
import numpy as np
import pandas as pd

pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 100)

In [2]:
#path = '/content/drive/MyDrive/O4DS - Project Work/goodreads_cleaned.csv'
path = 'DATA/goodreads_cleaned.csv'

In [3]:
df = pd.read_csv(path, sep = ";")
df

user_id   book_id  rating
0       8842281e1d1347389f2ab93d60773d4d  18245960       5
1       8842281e1d1347389f2ab93d60773d4d     16981       3
2       8842281e1d1347389f2ab93d60773d4d  28684704       3
3       8842281e1d1347389f2ab93d60773d4d  27161156       0
4       8842281e1d1347389f2ab93d60773d4d  25884323       4
...                                  ...       ...     ...
899995  b9450d1c1f97f891c392b1105959b56e  11832081       3
899996  b9450d1c1f97f891c392b1105959b56e  16095092       3
899997  b9450d1c1f97f891c392b1105959b56e   8430896       4
899998  b9450d1c1f97f891c392b1105959b56e  12275680       4
899999  b9450d1c1f97f891c392b1105959b56e     17005       3

[900000 rows x 3 columns]

## Data Exploration

In [4]:
df.user_id.value_counts().describe()

count    12188.000000
mean        73.843124
std        103.860677
min          1.000000
25%         14.000000
50%         37.000000
75%         92.000000
max       1815.000000
Name: user_id, dtype: float64

In [5]:
df.book_id.value_counts().describe()

count    25474.000000
mean        35.330141
std         67.222413
min          1.000000
25%         10.000000
50%         17.000000
75%         34.000000
max       1734.000000
Name: book_id, dtype: float64

## Data Cleaning

In [6]:
df['book_id_count'] = df.groupby('book_id')['book_id'].transform('count')
df['user_id_count'] = df.groupby('user_id')['user_id'].transform('count')
df.book_id_count.quantile(0.9)

457.0

In [7]:
book_quantile = 0.9
user_quantile = 0.25

df = df.loc[(df.book_id_count >= df.book_id.value_counts().quantile(book_quantile)) & (df.user_id_count >= df.user_id.value_counts().quantile(user_quantile)),:]


In [8]:
df.shape

(425794, 5)

## Data Pivoting

In [9]:
df = pd.pivot_table(df, columns="book_id", index="user_id", values="rating")
df.head(100)

book_id                           1         2         3         5         \
user_id                                                                    
000a1016fda6008d1edbba720ca00851       NaN       NaN       NaN       NaN   
0011e1a9112b3d798702ef5b20bbf35b       NaN       NaN       NaN       NaN   
0019de4561419b7543238e0979f2f33e       NaN       NaN       NaN       NaN   
00204424763e8233c5f53f0729f2304f       NaN       NaN       NaN       NaN   
00214d8b0a020837cccf5f41eb563037       NaN       NaN       NaN       NaN   
00238d8a4c276c47f5d5e242f54a8f28       NaN       NaN       NaN       NaN   
002a023d3de233b4bd3ec4fc3e9c581a       NaN       NaN       NaN       NaN   
002e063d40ae0107a59d8f9c1aa7a423       NaN       NaN       NaN       NaN   
005238c5743d61b58e49d5da089e43df       NaN       NaN       NaN       NaN   
005a572f0bfe510fa796e6eadc6a2eb4       NaN       NaN       NaN       NaN   
005f902ce947f147fbb880420553d52e       NaN       NaN       NaN       NaN   
00608f34a76da8ba3ed37b25f263adf4       NaN       NaN       NaN       NaN   
00624f09513d2322b41cdbcb73853b6c       NaN       NaN       NaN       NaN   
006beedd060f70067eac5540b9c375bb       NaN       NaN       NaN       NaN   
006f552534b15a7358a125f7505e0eea       NaN       NaN       NaN       NaN   
00735b5ea2c10159ae8c571a4a10fa88       NaN       NaN       NaN       NaN   
0077175036682322b87cf93f6bdbd30f       NaN       NaN       NaN       NaN   
007d939b748568b27d1ec164e12d4b8a       NaN       NaN       NaN       NaN   
0088ac052921fbdad6145c29322f9144       NaN       NaN       NaN       NaN   
009033078efdad45c1eceeb92d159237       NaN       NaN       NaN       NaN   
009235f414f42cfd0f76282f6aefe6c1       NaN       NaN       5.0       5.0   
0094c87e3b8c40fbbf7fe6e796020648       NaN       NaN       NaN       NaN   
009a47e49c0dc6e84d1c5e0eb4cdf7f6       NaN       NaN       NaN       NaN   
009abcb92443d0c048847ed0b8d2ecf0       NaN       NaN       NaN       NaN   
00aabc1cf5b62cff6f5274a593c96b4e       NaN       NaN       NaN       NaN   
00af7569ab6ee719f3b940dfda65bb3f       NaN       NaN       NaN       NaN   
00b5b129cc3cfa6511418cce1cec54ab       NaN       NaN       NaN       NaN   
00c484920796bba4529e9c1514a2f57f       NaN       NaN       NaN       NaN   
00c7135b2305f50cb384a85785fb4fbf       NaN       NaN       NaN       NaN   
00d6b283f77415fbb08db4c8c65c016d       NaN       NaN       NaN       NaN   
00efe9bf7f110572763cac91479965c5       NaN       NaN       NaN       NaN   
00f401f4d493eea391011082de03de07       NaN       NaN       NaN       NaN   
00f70d68cbeb3332407069bf801213f7       NaN       NaN       NaN       NaN   
00feeb3952f562e06632057ecd880508       NaN       NaN       NaN       NaN   
01001347e5bab7241212a0a6910260f8       NaN       NaN       NaN       NaN   
0102db8db2097cd4482ebc20b7b2d5be       NaN       NaN       NaN       NaN   
0110a199dc5638247be7a096898b1317       NaN       NaN       NaN       NaN   
01123b14590a1ac22fe172aab20129a3       NaN       NaN       NaN       NaN   
0112f1272ed7ed5968d3feb0f3431158       NaN       NaN       NaN       NaN   
011317536f296c2502650e31e1d7d6e0       NaN       NaN       NaN       NaN   
011375c417e89f0c77c96e6335a4e185       NaN       NaN       NaN       NaN   
0118d9d0a565b11b7ff9edcaace80f75       NaN       NaN       NaN       NaN   
01395525afb150e03704b2f7be70e29b       NaN       NaN       NaN       NaN   
013ef437e9e8f8c0968f952548165cc9       NaN       NaN       NaN       NaN   
01417cc1a3e78a0f84553ab6adbb337d       NaN       NaN       NaN       NaN   
014bafb43282fbb49eecaa466538fd1f       NaN       NaN       NaN       NaN   
01513f4c5488498d952a32a3337452d8       NaN       NaN       NaN       NaN   
01546af41b83c0b4141b11c19e8c35af       NaN       NaN       NaN       NaN   
015988b10cec9949eb29663fcac897f5       NaN       NaN       NaN       NaN   
015faffa5d679d223ac360c7844f507a       NaN       NaN       NaN       NaN   
0163d7cbed017f77007e22d37510b21c       NaN      

## Convert to an array to work with the matrix

In [10]:
df.reset_index(drop=True)
df

book_id                           1         2         3         5         \
user_id                                                                    
000a1016fda6008d1edbba720ca00851       NaN       NaN       NaN       NaN   
0011e1a9112b3d798702ef5b20bbf35b       NaN       NaN       NaN       NaN   
0019de4561419b7543238e0979f2f33e       NaN       NaN       NaN       NaN   
00204424763e8233c5f53f0729f2304f       NaN       NaN       NaN       NaN   
00214d8b0a020837cccf5f41eb563037       NaN       NaN       NaN       NaN   
...                                    ...       ...       ...       ...   
fff3a250fbc018ad2c2c2d45c86734da       NaN       NaN       NaN       NaN   
fff7bfd82b89fa347edfe9a82ac0c61b       NaN       NaN       NaN       NaN   
fffc34d137f5c5c5e1ca1d6f325a4dcf       NaN       NaN       NaN       NaN   
fffce7dae5ac5e8fb6288d81658ececc       NaN       NaN       NaN       NaN   
ffff7cafdaf5196383cb2efca08fb6fe       NaN       5.0       NaN       NaN   

book_id                           6         11        34        295       \
user_id                                                                    
000a1016fda6008d1edbba720ca00851       NaN       NaN       NaN       NaN   
0011e1a9112b3d798702ef5b20bbf35b       NaN       NaN       NaN       NaN   
0019de4561419b7543238e0979f2f33e       NaN       NaN       NaN       NaN   
00204424763e8233c5f53f0729f2304f       NaN       NaN       NaN       NaN   
00214d8b0a020837cccf5f41eb563037       NaN       NaN       NaN       NaN   
...                                    ...       ...       ...       ...   
fff3a250fbc018ad2c2c2d45c86734da       NaN       NaN       NaN       NaN   
fff7bfd82b89fa347edfe9a82ac0c61b       NaN       NaN       NaN       NaN   
fffc34d137f5c5c5e1ca1d6f325a4dcf       NaN       NaN       NaN       NaN   
fffce7dae5ac5e8fb6288d81658ececc       NaN       NaN       NaN       NaN   
ffff7cafdaf5196383cb2efca08fb6fe       NaN       NaN       NaN       NaN   

book_id                           320       343       350       662       \
user_id                                                                    
000a1016fda6008d1edbba720ca00851       NaN       NaN       NaN       NaN   
0011e1a9112b3d798702ef5b20bbf35b       NaN       NaN       NaN       NaN   
0019de4561419b7543238e0979f2f33e       NaN       NaN       NaN       NaN   
00204424763e8233c5f53f0729f2304f       NaN       NaN       NaN       NaN   
00214d8b0a020837cccf5f41eb563037       NaN       NaN       NaN       NaN   
...                                    ...       ...       ...       ...   
fff3a250fbc018ad2c2c2d45c86734da       NaN       NaN       NaN       NaN   
fff7bfd82b89fa347edfe9a82ac0c61b       NaN       NaN       NaN       NaN   
fffc34d137f5c5c5e1ca1d6f325a4dcf       NaN       NaN       NaN       NaN   
fffce7dae5ac5e8fb6288d81658ececc       NaN       NaN       NaN       NaN   
ffff7cafdaf5196383cb2efca08fb6fe       NaN       NaN       NaN       NaN   

book_id                           667       830       865       890       \
user_id                                                                    
000a1016fda6008d1edbba720ca00851       NaN       NaN       NaN       NaN   
0011e1a9112b3d798702ef5b20bbf35b       NaN       NaN       NaN       NaN   
0019de4561419b7543238e0979f2f33e       NaN       NaN       NaN       NaN   
00204424763e8233c5f53f0729f2304f       NaN       NaN       NaN       NaN   
00214d8b0a020837cccf5f41eb563037       NaN       NaN       NaN       NaN   
...                                    ...       ...       ...       ...   
fff3a250fbc018ad2c2c2d45c86734da       NaN       NaN       NaN       NaN   
fff7bfd82b89fa347edfe9a82ac0c61b       NaN       NaN       NaN       NaN   
fffc34d137f5c5c5e1ca1d6f325a4dcf       NaN       NaN       NaN       NaN   
fffce7dae5ac5e8fb6288d81658ececc       NaN       NaN       NaN       NaN   
ffff7cafdaf5196383cb2efca08fb6fe       NaN       NaN       NaN       NaN   

book_id                           902       

In [11]:
data_matrix = df.to_numpy(na_value=np.nan)
print(data_matrix)

[[nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 ...
 [nan nan nan ... nan nan nan]
 [nan nan nan ... nan nan nan]
 [nan  5. nan ... nan nan nan]]


In [12]:
# Check how to get the index of not empty values
idx = np.argwhere(~np.isnan(data_matrix))
print(idx)

[[   0  419]
 [   0  427]
 [   0  495]
 ...
 [9152 2452]
 [9152 2475]
 [9152 2559]]


In [14]:
print(data_matrix[idx[:,0], idx[:,1]])

[5. 4. 5. ... 5. 2. 3.]


# Frank-Wolfe - standard algorithm

- Should we feed $\delta$ to the FW algorithm or should it be defined based on the dimensions of the data?
- Which is the correct objective function?
- Initialize with random matrix of integers from 1 to 5 or with zeros matrix?

In [25]:
from scipy import sparse
from scipy import stats

In [41]:
def FW_objective_function(diff_vec):
    return 0.5*(np.power(diff_vec,2).sum())
    #return 0.5 * LA.norm(diff_vec, 2)**2

def FrankWolfe(X, objective_function, Z_init=None, max_iter=150, patience=1e-3):
    '''
    :param X: sparse matrix with ratings and 'empty values', rows - users, columns - books.
    :param objective_function: objective function that we would like to minimize with FW
    :param Z_init: In case we want to initialize Z with a known matrix, if not given Z_init will be a zeros matrix
    :param max_iter: max number of iterations for the method
    :param patience: once reached this tolerance provide the result
    :return: Z: matrix of predicted ratings - it should be like X but with no 'empty values'
            accuracy: difference between original values (X) and predicted ones (Z)
    '''

    # Get X indexes for not empty values
    idx_ratings = np.argwhere(~np.isnan(X))
    idx_rows = idx_ratings[:,0]
    idx_cols = idx_ratings[:,1]

    # Initialize Z -- think about a good init
    if Z_init is not None:
        Z = Z_init
    else:
        #Z = np.random.randint(0, 6, size=X.shape)
        Z = np.zeros(X.shape)

    # Create vectors with the not empty features of the sparse matrix
    X_rated = X[idx_rows, idx_cols]
    Z_rated = Z[idx_rows, idx_cols]
    diff_vec = Z_rated - X_rated

    #delta = 300 # choose an appropriate one
    delta = min(X.shape)**2 * np.linalg.norm(X_rated, 2)
    diff_err = patience + 1
    err = objective_function(diff_vec)
    it = 0
    while (diff_err > patience) and (it < max_iter):

        # Gradient
        grad = sparse.csr_matrix((diff_vec, (idx_rows, idx_cols)))

        # SVD
        u_max, s_max, v_max = sparse.linalg.svds(grad, k = 1, which='LM')   # Compute k = 1 singular values, starting from the largest (which = 'LM')

        # Update
        update_Z = -delta*np.outer(u_max,v_max)     # Zk_tilde in the theory

        #alpha - as studied in class
        alpha_k = 2/(it+1)
        Z = (1-alpha_k)*Z + alpha_k*update_Z

        # Error
        diff_vec = Z[idx_rows, idx_cols] - X[idx_rows, idx_cols]
        new_err = objective_function(diff_vec)

        # Improvement at this iteration
        diff_err = np.abs(err - new_err)
        err = new_err

        print('Iteration:', it, 'Err:', err, 'Diff err:', diff_err)

        # Count iteration
        it += 1
    return Z, err

We build a smaller matrix for testing the FW alg, then we will apply it to our data

In [30]:
# Create a random sparse matrix for testing
rvs = stats.randint(1,6).rvs
X_test = sparse.random(1000, 500,              # shape of the sparse matrix
            density = 0.05,             # density of the sparse matrix
            dtype = np.int32,           # data type
            data_rvs=rvs).toarray()     # distribution

In [42]:
pred_ratings, loss = FrankWolfe(X_test, FW_objective_function, Z_init=result_10000it, max_iter=10000, patience=1e-7)

Iteration: 0 Err: 3.4507671903458056e+16 Diff err: 3.4507671815594436e+16
Iteration: 1 Err: 8626076975931593.0 Diff err: 2.5881594927526464e+16
Iteration: 2 Err: 958446563762380.8 Diff err: 7667630412169212.0
Iteration: 3 Err: 958456214291431.6 Diff err: 9650529050.875
Iteration: 4 Err: 345039604979301.25 Diff err: 613416609312130.4
Iteration: 5 Err: 345045395296732.25 Diff err: 5790317431.0
Iteration: 6 Err: 176040024004240.66 Diff err: 169005371292491.6
Iteration: 7 Err: 176044159945262.88 Diff err: 4135941022.21875
Iteration: 8 Err: 106492990481940.31 Diff err: 69551169463322.56
Iteration: 9 Err: 106496207324957.72 Diff err: 3216843017.40625
Iteration: 10 Err: 71288456884055.39 Diff err: 35207750440902.33
Iteration: 11 Err: 71291088846523.92 Diff err: 2631962468.53125
Iteration: 12 Err: 51040676556262.71 Diff err: 20250412290261.21
Iteration: 13 Err: 51042903601428.05 Diff err: 2227045165.3359375
Iteration: 14 Err: 38337090640667.57 Diff err: 12705812960760.477
Iteration: 15 Err: 38

In [43]:
pred_ratings

array([[-20.29747146, -30.66891536, -20.3627673 , ..., -25.74757726,
        -21.4650664 , -24.58530659],
       [-14.26166015, -21.54897219, -14.30753911, ..., -18.09108081,
        -15.08205012, -17.27443183],
       [-16.75098341, -25.31027047, -16.80487039, ..., -21.24881616,
        -17.71456961, -20.28962394],
       ...,
       [-10.9550332 , -16.55275075, -10.99027493, ..., -13.8965863 ,
        -11.58521225, -13.26928088],
       [-14.75859843, -22.29983213, -14.80607602, ..., -18.72145278,
        -15.60757437, -17.8763482 ],
       [-14.95812976, -22.60131842, -15.00624923, ..., -18.97456057,
        -15.81858357, -18.11803046]])

In [44]:
result_10000it

array([[-20.29747146, -30.66891536, -20.3627673 , ..., -25.74757726,
        -21.4650664 , -24.58530659],
       [-14.26166015, -21.54897219, -14.30753911, ..., -18.09108081,
        -15.08205012, -17.27443183],
       [-16.75098341, -25.31027047, -16.80487039, ..., -21.24881616,
        -17.71456961, -20.28962394],
       ...,
       [-10.9550332 , -16.55275075, -10.99027493, ..., -13.8965863 ,
        -11.58521225, -13.26928088],
       [-14.75859843, -22.29983213, -14.80607602, ..., -18.72145278,
        -15.60757437, -17.8763482 ],
       [-14.95812976, -22.60131842, -15.00624923, ..., -18.97456057,
        -15.81858357, -18.11803046]])

#### Our data prediction

In [ ]:
pred_ratings, loss = FrankWolfe(data_matrix, FW_objective_function, max_iter=10000, patience=1e-5)

# Frank-Wolfe 2

## Sub-Chapter